# Generated by Django 4.0.3 on 2022-03-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timeStemp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
