# Generated by Django 4.0.3 on 2022-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timeStemp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
